---
# tasks file for virtualbox (CentOS specific)

- name: Configure Oracle VirtualBox YUM repository
  template: >
    src=virtualbox.repo.j2
    dest=/etc/yum.repos.d/virtualbox.repo
    owner=root
    group=root
    mode=0644
  tags: virtualbox

- name: Install VirtualBox packages
  yum: name={{ virtualbox_packages }} state=present
  tags: virtualbox
  register: pkg_result
  until: pkg_result is success
## mostly for travis to avoid stalling "No output has been received in the last 10m0s"...
  async: 1200
  poll: 15
